### ISSUE TITLE
Admin Login

### ISSUE THREAD

**Issue by amanovishnu** [CapstoneProject18/Online-Food-Diary#12]
as a admin i want a separate login page so that i can login into admin panel

Acceptance Criteria:
as a admin on the homepage of the application there should be a seperate link on the navbar for admin. on clicking the link admin will be routed to a page where two textbox and button are present on entering the credentials. the admin will be redirected to the admin panel else he will be displayed a warning of wrong password

**Comment by GeekyShiva** [comment]
Irrelevant feature
