### ISSUE TITLE
Google & Facebook (User Signup)

### ISSUE THREAD

**Issue by amanovishnu** [CapstoneProject18/Online-Food-Diary#5]
As a User i Want third party signup so that i can signup using my google/Facebook account.

Acceptance Criteria:
As a Legit user whenever i click on signup button i will routed to  a new page where there will be two button with names google and Facebook when these buttons are clicked a popup should appear asking the credentials of these apps and successful signup a automatic available username should be generated for user.

**Comment by GeekyShiva** [comment]
Irrelevant
